# Single Layer Neural Network

In [1]:
import torch

In [2]:
def activation(x):
    
    return 1/(1+torch.exp(-x))

In [3]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [4]:
y = activation(torch.sum(features*weights) + bias)

In [5]:
y

tensor([[0.1595]])

In [8]:
y=activation(torch.mm(features,weights.view(5,1))+bias)
print(y)

tensor([[0.1595]])


# Multi Layer Neural Network

In [12]:
torch.manual_seed(7)
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn(n_input,n_hidden)
W2 = torch.randn(n_hidden,n_output)

B1= torch.randn(1,n_hidden)
B2= torch.randn(1,n_output)

In [14]:
h = activation(torch.mm(features,W1)+ B1)
output = activation(torch.mm(h,W2)+B2)
print(output)

tensor([[0.3171]])
